/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package forms;

import javax.swing.JOptionPane;

/**
 *
 * @author valdi
 */
public class Main extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Main.class.getName());

    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbTitulo = new javax.swing.JLabel();
        lbValor = new javax.swing.JLabel();
        tfValor = new javax.swing.JTextField();
        cbMoedaConversao = new javax.swing.JComboBox<>();
        lbMoedaConversao = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Conversor de Moedas");

        lbTitulo.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lbTitulo.setText("Conversor de Moedas");

        lbValor.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lbValor.setText("Digite o valor em reais (R$):");

        cbMoedaConversao.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        cbMoedaConversao.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Dólar (USD)", "Euro (EUR)", "Libra (GBP)", "Peso Argentino (ARS)", "Iene Japonês (JPY)" }));

        lbMoedaConversao.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lbMoedaConversao.setText("Moeda para conversão:");

        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButton1.setText("Converter");
        jButton1.addActionListener(this::jButton1ActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lbMoedaConversao)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cbMoedaConversao, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lbValor)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(tfValor, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(160, 160, 160)
                        .addComponent(lbTitulo)))
                .addGap(166, 166, 166))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jButton1)
                .addGap(200, 200, 200))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbTitulo)
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbValor)
                    .addComponent(tfValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbMoedaConversao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbMoedaConversao))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 124, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(26, 26, 26))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if (tfValor.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Por favor, preencha o campo de Valor.", "Campo Vazio", JOptionPane.WARNING_MESSAGE);
            return;
        }
        // Acesso Combo Box
        String moeda = cbMoedaConversao.getSelectedItem().toString();

        try {
            String textoValor = tfValor.getText().replace(",", ".");
            float valorEmReais = Float.parseFloat(textoValor);

            if (valorEmReais <= 0) {
                JOptionPane.showMessageDialog(this, "Valor deve ser maior que zero.", "Valor Inválido", JOptionPane.ERROR_MESSAGE);
                return;
            }

            double valorConvertido = 0;
            if ("Dólar (USD)".equals(moeda)) {
                valorConvertido = valorEmReais / 5.6;
            } else if ("Euro (EUR)".equals(moeda)) {
                valorConvertido = valorEmReais / 6.1;
            } else if ("Libra (GBP)".equals(moeda)) {
                valorConvertido = valorEmReais / 7;
            } else if ("Peso Argentino (ARS)".equals(moeda)) {
                valorConvertido = valorEmReais / 0.03;
            } else if ("Iene Japonês (JPY)".equals(moeda)) {
                valorConvertido = valorEmReais * 29.36;
            }

            String resultadoFormatado = String.format("Valor em Reais (R$): %.2f\nValor em %s: %.2f", valorEmReais, moeda, valorConvertido);

            JOptionPane.showMessageDialog(this, resultadoFormatado, "Resultado da Conversão", JOptionPane.INFORMATION_MESSAGE);

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Digite apenas número válido para Valor.", "Erro de Formato", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cbMoedaConversao;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel lbMoedaConversao;
    private javax.swing.JLabel lbTitulo;
    private javax.swing.JLabel lbValor;
    private javax.swing.JTextField tfValor;
    // End of variables declaration//GEN-END:variables
}
