/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package forms;

import javax.swing.ButtonModel;
import javax.swing.JOptionPane;

/**
 *
 * @author 0082934
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgDisc = new javax.swing.ButtonGroup();
        rbLP = new javax.swing.JRadioButton();
        rbBD = new javax.swing.JRadioButton();
        cbCampus = new javax.swing.JComboBox<>();
        btOk = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        bgDisc.add(rbLP);
        rbLP.setText("Linguagem de Programação I");
        rbLP.setActionCommand("1");

        bgDisc.add(rbBD);
        rbBD.setText("Banco de Dados");
        rbBD.setActionCommand("2");

        cbCampus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "São João Evangelista", "Ipatinga", "Governador Valadares", "Belo Horizonte", "Bambuí", "Ponte Nova", "Ouro Preto" }));

        btOk.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btOk.setText("OK");
        btOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btOkActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rbBD)
                    .addComponent(rbLP)
                    .addComponent(cbCampus, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btOk, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(516, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addComponent(rbLP)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rbBD)
                .addGap(79, 79, 79)
                .addComponent(cbCampus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(57, 57, 57)
                .addComponent(btOk)
                .addContainerGap(169, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btOkActionPerformed
        // TODO add your handling code here:
        
        // Primeira forma
        /*
        if(rbLP.isSelected()){
            JOptionPane.showMessageDialog(this, "LPR I");
        }
        
        if(rbBD.isSelected()){
            JOptionPane.showMessageDialog(this, "BD");
        }
        */
        // Segunda forma
        ButtonModel sel = bgDisc.getSelection();
        if(sel != null){
            String op = sel.getActionCommand();
            JOptionPane.showMessageDialog(this, op);
        }
        
        // Acesso Combo Box
        String campus = cbCampus.getSelectedItem().toString();
        JOptionPane.showMessageDialog(this, campus);
    }//GEN-LAST:event_btOkActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bgDisc;
    private javax.swing.JButton btOk;
    private javax.swing.JComboBox<String> cbCampus;
    private javax.swing.JRadioButton rbBD;
    private javax.swing.JRadioButton rbLP;
    // End of variables declaration//GEN-END:variables
}
