/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package forms;

import javax.swing.ButtonModel;
import javax.swing.JOptionPane;

/**
 *
 * @author valdi
 */
public class Main extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Main.class.getName());

    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgSexo = new javax.swing.ButtonGroup();
        lbTitulo = new javax.swing.JLabel();
        lbPeso = new javax.swing.JLabel();
        lbAltura = new javax.swing.JLabel();
        lbSexo = new javax.swing.JLabel();
        tfPeso = new javax.swing.JTextField();
        tfAltura = new javax.swing.JTextField();
        rbMasculino = new javax.swing.JRadioButton();
        rbFeminino = new javax.swing.JRadioButton();
        btOK = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Calculadora de IMC");

        lbTitulo.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lbTitulo.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbTitulo.setText("Calculadora de IMC (Índice de Massa Corporal)");

        lbPeso.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lbPeso.setText("Digite seu peso (quilogramas):");

        lbAltura.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lbAltura.setText("Digite sua altura (metros):");

        lbSexo.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lbSexo.setText("Escolha seu sexo:");

        bgSexo.add(rbMasculino);
        rbMasculino.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        rbMasculino.setText("Masculino");
        rbMasculino.setActionCommand("M");

        bgSexo.add(rbFeminino);
        rbFeminino.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        rbFeminino.setText("Feminino");
        rbFeminino.setActionCommand("F");

        btOK.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btOK.setText("Calcular IMC");
        btOK.addActionListener(this::btOKActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbPeso)
                            .addComponent(lbAltura))
                        .addGap(3, 3, 3)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfAltura, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfPeso, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(lbTitulo))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(lbSexo)
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btOK)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(rbMasculino)
                                .addGap(41, 41, 41)
                                .addComponent(rbFeminino)))))
                .addContainerGap(53, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbTitulo)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbPeso)
                    .addComponent(tfPeso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbAltura)
                    .addComponent(tfAltura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbSexo)
                    .addComponent(rbMasculino)
                    .addComponent(rbFeminino))
                .addGap(45, 45, 45)
                .addComponent(btOK)
                .addContainerGap(56, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btOKActionPerformed

        if (tfPeso.getText().trim().isEmpty() || tfAltura.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Por favor, preencha os campos de Peso e Altura.", "Campo Vazio", JOptionPane.WARNING_MESSAGE);
            return;
        }

        if (bgSexo.getSelection() == null) {
            JOptionPane.showMessageDialog(this, "Por favor, selecione o Sexo (Masculino ou Feminino).", "Sexo não selecionado", JOptionPane.WARNING_MESSAGE);
            return;
        }

        try {
            String textoPeso = tfPeso.getText().replace(",", ".");
            String textoAltura = tfAltura.getText().replace(",", ".");

            float peso = Float.parseFloat(textoPeso);
            float altura = Float.parseFloat(textoAltura);

            if (peso <= 0 || altura <= 0) {
                JOptionPane.showMessageDialog(this, "Peso e Altura devem ser valores maiores que zero.", "Valor Inválido", JOptionPane.ERROR_MESSAGE);
                return;
            }

            float imc = peso / (altura * altura);
            String classificacao = "";

            String op = bgSexo.getSelection().getActionCommand();

            if ("M".equals(op)) {
                if (imc < 20.7) {
                    classificacao = "Abaixo do Peso";
                } else if (imc < 26.4) {
                    classificacao = "Peso Normal";
                } else if (imc < 27.8) {
                    classificacao = "Sobrepeso";
                } else if (imc < 31.1) {
                    classificacao = "Obesidade Leve";
                } else {
                    classificacao = "Obesidade";
                }
            } else {
                if (imc < 19.1) {
                    classificacao = "Abaixo do Peso";
                } else if (imc < 25.8) {
                    classificacao = "Peso Normal";
                } else if (imc < 27.3) {
                    classificacao = "Sobrepeso";
                } else if (imc < 32.3) {
                    classificacao = "Obesidade Leve";
                } else {
                    classificacao = "Obesidade";
                }
            }

            String resultadoFormatado = String.format("Classificação: %s\nIMC= %.2f", classificacao, imc);

            JOptionPane.showMessageDialog(this, resultadoFormatado, "Resultado do IMC", JOptionPane.INFORMATION_MESSAGE);

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Digite apenas números válidos para Peso e Altura.", "Erro de Formato", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btOKActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bgSexo;
    private javax.swing.JButton btOK;
    private javax.swing.JLabel lbAltura;
    private javax.swing.JLabel lbPeso;
    private javax.swing.JLabel lbSexo;
    private javax.swing.JLabel lbTitulo;
    private javax.swing.JRadioButton rbFeminino;
    private javax.swing.JRadioButton rbMasculino;
    private javax.swing.JTextField tfAltura;
    private javax.swing.JTextField tfPeso;
    // End of variables declaration//GEN-END:variables
}
