/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package forms;

import com.valdir.telalogin.ConnectionFactory;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author 0082934
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbSenha = new javax.swing.JLabel();
        lbNome1 = new javax.swing.JLabel();
        tfSenha = new javax.swing.JTextField();
        tfEmail1 = new javax.swing.JTextField();
        lbTitulo = new javax.swing.JLabel();
        btOk = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Tela de Login");

        lbSenha.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lbSenha.setText("Digite sua senha:");

        lbNome1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lbNome1.setText("Digite seu e-mail:");

        tfSenha.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N

        tfEmail1.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N

        lbTitulo.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        lbTitulo.setText("Login");

        btOk.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btOk.setText("Efetuar Login");
        btOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btOkActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lbSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tfSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lbNome1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tfEmail1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(236, 236, 236)
                        .addComponent(lbTitulo))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(210, 210, 210)
                        .addComponent(btOk)))
                .addContainerGap(197, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(lbTitulo)
                .addGap(56, 56, 56)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbNome1)
                    .addComponent(tfEmail1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbSenha)
                    .addComponent(tfSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(60, 60, 60)
                .addComponent(btOk)
                .addContainerGap(119, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btOkActionPerformed
        Connection conn = ConnectionFactory.getConexao();

        if (conn != null) {

            if (tfEmail1.getText().trim().isEmpty() || tfSenha.getText().trim().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Por favor, preencha os campos de E-mail e Senha.", "Campo Vazio", JOptionPane.WARNING_MESSAGE);
                return;
            }

            try {
                String email = tfEmail1.getText();
                String senha = tfSenha.getText();

                // Preparar o comadndo sql
                String sql = "select * from clientes where email = (?) and senha = (?);";

                // Preparar o comadndo sql
                PreparedStatement stmt = conn.prepareStatement(sql);
                stmt.setString(1, email);
                stmt.setString(2, senha);

                ResultSet rs = stmt.executeQuery(sql);
                String resultadoFormatado = "";
                if (rs.getString(email) != null && rs.getString(senha) != null) {
                    resultadoFormatado = String.format("Seja bem-vindo %s!", email);
                } else {
                    resultadoFormatado = String.format("E-mail %s não encontrado!", email);
                }

                conn.close();

                JOptionPane.showMessageDialog(this, resultadoFormatado, "Verificação", JOptionPane.INFORMATION_MESSAGE);
            } catch (SQLException ex) {
                System.out.println("Erro do BD: " + ex.getMessage());
            }

        } else {
            System.out.println("Erro na conexao com BD!");
        }
    }//GEN-LAST:event_btOkActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btOk;
    private javax.swing.JLabel lbNome1;
    private javax.swing.JLabel lbSenha;
    private javax.swing.JLabel lbTitulo;
    private javax.swing.JTextField tfEmail1;
    private javax.swing.JTextField tfSenha;
    // End of variables declaration//GEN-END:variables
}
